name: authTests

on: pull_request

jobs:

  build:
    runs-on: 
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -count=1 -failfast ./...
